# Generated by Django 5.2.5 on 2025-10-17 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='wallet', help_text='Ícone representativo do módulo', max_length=50)),
                ('cor', models.CharField(default='#008445', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=1)),
                ('slug', models.SlugField(help_text="Identificador usado na URL (ex: 'gestao', 'planejamento')", unique=True)),
            ],
            options={
                'verbose_name': 'Módulo de Aprendizagem',
                'verbose_name_plural': 'Módulos de Aprendizagem',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='publico_alvo',
            field=models.CharField(blank=True, help_text='Ex: Ensino Fundamental, Médio, Adultos', max_length=100),
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz Interativo'), ('simulacao', 'Simulação'), ('dilema', 'Dilema Interativo')], default='quiz', max_length=50)),
                ('ordem', models.IntegerField(default=1)),
                ('pontos_base', models.IntegerField(default=100)),
                ('ativo', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desafio', to='game.quiz')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='game.modulo')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['modulo', 'ordem'],
                'unique_together': {('modulo', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='resultado',
            name='desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='game.desafio'),
        ),
        migrations.CreateModel(
            name='ProgressoDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('pontuacao', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='game.desafio')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_desafios', to='game.estudante')),
            ],
            options={
                'verbose_name': 'Progresso de Desafio',
                'verbose_name_plural': 'Progresso de Desafios',
                'unique_together': {('estudante', 'desafio')},
            },
        ),
    ]
